# Generated by Django 5.2.6 on 2026-06-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_room_type_room_total_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Room Booking', max_length=200)),
                ('hero_subtitle', models.TextField(default='Comfortable & Premium Stay For Your Guests')),
                ('hero_image', models.ImageField(upload_to='room_page/')),
            ],
        ),
    ]
