# Generated by Django 5.2.6 on 2026-06-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusection',
            name='has_category',
            field=models.BooleanField(default=False),
        ),
    ]
