# Generated by Django 5.2.6 on 2026-06-20 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_menusection_has_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_count', models.PositiveIntegerField()),
                ('price_per_plate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_pricing', to='catering.cateringpackage')),
            ],
        ),
    ]
