# Generated by Django 5.2.6 on 2026-06-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_guestpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_features', to='catering.cateringpackage')),
            ],
        ),
    ]
