# Generated by Django 5.2.6 on 2026-06-30 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_bannarfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannarfeature',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bannar_features', to='catering.cateringpackage'),
        ),
    ]
