# Generated by Django 5.2.6 on 2026-07-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0005_alter_bannarfeature_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringpackage',
            name='icon',
        ),
        migrations.AddField(
            model_name='cateringpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catering'),
        ),
    ]
