# Generated by Django 5.2.6 on 2026-06-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='is_ac',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hall',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hall',
            name='parking_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hall',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
