# Generated by Django 5.2.6 on 2026-06-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_hall_is_ac_hall_is_featured_hall_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
