# Generated by Django 5.2.6 on 2026-07-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_alter_hall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='hall/banner/'),
        ),
        migrations.AddField(
            model_name='hall',
            name='show_badge',
            field=models.BooleanField(default=False),
        ),
    ]
