# Generated by Django 5.2.6 on 2026-07-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_hall_banner_image_hall_show_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='is_wifi',
            field=models.BooleanField(default=True),
        ),
    ]
