# Generated by Django 5.2.6 on 2026-07-02 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_hallfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_image', models.ImageField(upload_to='hall/gallery/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='halls.hall')),
            ],
        ),
    ]
