# Generated by Django 5.2.6 on 2026-07-02 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0007_hallgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_categories', to='halls.hall')),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=30)),
                ('default_quantity', models.PositiveIntegerField(default=0)),
                ('min_quantity', models.PositiveIntegerField(default=0)),
                ('max_quantity', models.PositiveIntegerField(default=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='halls.furniturecategory')),
            ],
        ),
    ]
