# Generated by Django 5.2.6 on 2026-07-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0009_furnitureitem_is_required_servicecategory_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
