# Generated by Django 5.2.6 on 2026-07-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0010_servicecategory_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
