# Generated by Django 5.2.6 on 2026-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0011_remove_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagedesign',
            name='description',
        ),
        migrations.AddField(
            model_name='stagecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
